### register request
POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "navid_rezaei_84",
    "email": "nr539118494@gmail.com",
    "mobile": "09103914537",
    "password": "123456",
    "confirm_password": "123456"
}
