### register request
POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "gdggd4",
    "email": "sfsf@gmail.com",
    "mobile": "09103914576",
    "password": "4546646",
    "confirm_password": "4546646"
}
